# Generated by Django 2.2.10 on 2021-03-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20210311_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, null=True)),
                ('parent_name', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('creator', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cfg_sys_department',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('use_authorize', models.TextField(null=True)),
                ('data_authorize', models.TextField(null=True)),
                ('data_create_authorize', models.TextField(null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('creator', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cfg_sys_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('user_pwd', models.CharField(max_length=50, null=True)),
                ('real_name', models.CharField(max_length=50, null=True)),
                ('msisdn', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('img_path', models.CharField(max_length=100, null=True)),
                ('role_id', models.IntegerField(null=True)),
                ('status', models.SmallIntegerField(null=True)),
                ('creator', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('department_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Department')),
            ],
            options={
                'db_table': 'cfg_sys_user',
            },
        ),
    ]
