# Generated by Django 2.2.10 on 2021-03-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_department_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ManyToManyField(null=True, to='user.Role'),
        ),
    ]
