# Generated by Django 2.2.10 on 2021-03-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210311_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='user.Department'),
        ),
    ]
